server:
  port: 9090

spring:
  application:
    name: consumer-service

eureka:
  instance:
    instance-id: consumer-microservice-instance
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
